type Collection {
	id: ID!
	name: String!
	slug: String!
	userId: String!
	items: [Item!]
}

type Query {
	userCollections(userId: ID!): [Collection!]!
}

type Mutation {
	createCollection(userId: ID!, name: String!): Collection!
	updateCollection(id: ID!, name: String!): Collection
	deleteCollection(id: ID!): Boolean!
}
