type Recipe {
	id: String!
	name: String!
	slug: String!
	itemId: String!
	item: Item
	quantity: Int!
	time: Int!
}

input IngredientInput {
	itemId: String!
	quantity: Int!
}

extend type Query {
	recipes(itemId: String!): [Recipe!]!
}

extend type Mutation {
	createRecipe(itemId: String!, name: String!, quantity: Int!, time: Int!): Recipe!
	updateRecipe(id: String!, name: String, quantity: Int, time: Int, ingredients: [IngredientInput!]): Recipe
	deleteRecipe(id: String!): Boolean!
}
